name: Android CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Set execute permissions for gradlew
      run: chmod +x gradlew 
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Tests
      run: ./gradlew test
